server:
  port: 8888

spring:
  rabbitmq:
    host: 192.168.174.128
    username: admin
    password: admin
    publisher-confirm-type: correlated #correlated发布消息成功到交换机后会触发回调方法 none：禁用发布确认，是默认值
    port: 5672